# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:       # permite executar manualmente pelo GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências
        run: dotnet restore ./src/backend/BolittosApi.csproj

      - name: Compilar projeto
        run: dotnet build ./src/backend/BolittosApi.csproj --configuration Release --no-restore

      - name: Publicar (gerar arquivos prontos pra deploy)
        run: dotnet publish ./src/backend/BolittosApi.csproj --configuration Release --output ./publish

      - name: Upload dos artefatos (para baixar no GitHub)
        uses: actions/upload-artifact@v4
        with:
          name: build-result
          path: ./publish
